//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 06:38:10 odp. CEST 
//


package jxtrozvrh;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for myDayType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="myDayType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Po"/>
 *     &lt;enumeration value="Út"/>
 *     &lt;enumeration value="St"/>
 *     &lt;enumeration value="Čt"/>
 *     &lt;enumeration value="Pá"/>
 *     &lt;enumeration value="So"/>
 *     &lt;enumeration value="Ne"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "myDayType")
@XmlEnum
public enum MyDayType {

    @XmlEnumValue("Po")
    PO("Po"),
    @XmlEnumValue("\u00dat")
    ÚT("\u00dat"),
    @XmlEnumValue("St")
    ST("St"),
    @XmlEnumValue("\u010ct")
    ČT("\u010ct"),
    @XmlEnumValue("P\u00e1")
    PÁ("P\u00e1"),
    @XmlEnumValue("So")
    SO("So"),
    @XmlEnumValue("Ne")
    NE("Ne");
    private final String value;

    MyDayType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MyDayType fromValue(String v) {
        for (MyDayType c: MyDayType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
