//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 06:38:10 odp. CEST 
//


package jxtrozvrh;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for myKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="myKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Př"/>
 *     &lt;enumeration value="Cv"/>
 *     &lt;enumeration value="Se"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "myKindType")
@XmlEnum
public enum MyKindType {

    @XmlEnumValue("P\u0159")
    PŘ("P\u0159"),
    @XmlEnumValue("Cv")
    CV("Cv"),
    @XmlEnumValue("Se")
    SE("Se");
    private final String value;

    MyKindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MyKindType fromValue(String v) {
        for (MyKindType c: MyKindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
