//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 06:38:10 odp. CEST 
//


package jxtrozvrh;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for myTimeTableSemesterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="myTimeTableSemesterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workDay" type="{}myTimeTableDayType" maxOccurs="7" minOccurs="7"/>
 *       &lt;/sequence>
 *       &lt;attribute name="semester" use="required" type="{}mySemesterType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "myTimeTableSemesterType", propOrder = {
    "workDay"
})
public class MyTimeTableSemesterType {

    @XmlElement(required = true)
    protected List<MyTimeTableDayType> workDay;
    @XmlAttribute(required = true)
    protected MySemesterType semester;

    /**
     * Gets the value of the workDay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workDay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MyTimeTableDayType }
     * 
     * 
     */
    public List<MyTimeTableDayType> getWorkDay() {
        if (workDay == null) {
            workDay = new ArrayList<MyTimeTableDayType>();
        }
        return this.workDay;
    }

    /**
     * Gets the value of the semester property.
     * 
     * @return
     *     possible object is
     *     {@link MySemesterType }
     *     
     */
    public MySemesterType getSemester() {
        return semester;
    }

    /**
     * Sets the value of the semester property.
     * 
     * @param value
     *     allowed object is
     *     {@link MySemesterType }
     *     
     */
    public void setSemester(MySemesterType value) {
        this.semester = value;
    }

}
