//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 06:38:10 odp. CEST 
//


package jxtrozvrh;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jxtrozvrh package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TimeTable_QNAME = new QName("", "timeTable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jxtrozvrh
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MyTimeTableItemType }
     * 
     */
    public MyTimeTableItemType createMyTimeTableItemType() {
        return new MyTimeTableItemType();
    }

    /**
     * Create an instance of {@link MySubjectType }
     * 
     */
    public MySubjectType createMySubjectType() {
        return new MySubjectType();
    }

    /**
     * Create an instance of {@link MyTimeTableType }
     * 
     */
    public MyTimeTableType createMyTimeTableType() {
        return new MyTimeTableType();
    }

    /**
     * Create an instance of {@link MyTimeTableSemesterType }
     * 
     */
    public MyTimeTableSemesterType createMyTimeTableSemesterType() {
        return new MyTimeTableSemesterType();
    }

    /**
     * Create an instance of {@link MyTimeTableDayType }
     * 
     */
    public MyTimeTableDayType createMyTimeTableDayType() {
        return new MyTimeTableDayType();
    }

    /**
     * Create an instance of {@link MyLocationType }
     * 
     */
    public MyLocationType createMyLocationType() {
        return new MyLocationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyTimeTableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timeTable")
    public JAXBElement<MyTimeTableType> createTimeTable(MyTimeTableType value) {
        return new JAXBElement<MyTimeTableType>(_TimeTable_QNAME, MyTimeTableType.class, null, value);
    }

}
