//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.31 at 10:40:44 dop. CEST 
//


package jxtsp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameters" type="{urn:x-herout:schemata:preregistration.1.0}parametersType"/>
 *         &lt;element name="processedData" type="{urn:x-herout:schemata:preregistration.1.0}processedDataType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="eventNo" use="required" type="{urn:x-herout:schemata:preregistration.1.0}eventNoType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventType", propOrder = {
    "parameters",
    "processedData"
})
public class EventType {

    @XmlElement(required = true)
    protected ParametersType parameters;
    @XmlElement(required = true)
    protected ProcessedDataType processedData;
    @XmlAttribute(required = true)
    protected BigInteger eventNo;

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersType }
     *     
     */
    public ParametersType getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersType }
     *     
     */
    public void setParameters(ParametersType value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the processedData property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessedDataType }
     *     
     */
    public ProcessedDataType getProcessedData() {
        return processedData;
    }

    /**
     * Sets the value of the processedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessedDataType }
     *     
     */
    public void setProcessedData(ProcessedDataType value) {
        this.processedData = value;
    }

    /**
     * Gets the value of the eventNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEventNo() {
        return eventNo;
    }

    /**
     * Sets the value of the eventNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEventNo(BigInteger value) {
        this.eventNo = value;
    }

}
