//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.31 at 10:40:44 dop. CEST 
//


package jxtsp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="kindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Cv"/>
 *     &lt;enumeration value="Se"/>
 *     &lt;enumeration value="Př"/>
 *     &lt;enumeration value="Neznámé"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "kindType", namespace = "urn:x-herout:schemata:timetable.1.0")
@XmlEnum
public enum KindType {

    @XmlEnumValue("Cv")
    CV("Cv"),
    @XmlEnumValue("Se")
    SE("Se"),
    @XmlEnumValue("P\u0159")
    PŘ("P\u0159"),
    @XmlEnumValue("Nezn\u00e1m\u00e9")
    NEZNÁMÉ("Nezn\u00e1m\u00e9");
    private final String value;

    KindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KindType fromValue(String v) {
        for (KindType c: KindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
