//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.31 at 10:40:44 dop. CEST 
//


package jxtsp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jxtsp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PreregistrationEvents_QNAME = new QName("urn:x-herout:schemata:preregistration.1.0", "preregistrationEvents");
    private final static QName _Term_QNAME = new QName("urn:x-herout:schemata:timetable.1.0", "term");
    private final static QName _Department_QNAME = new QName("urn:x-herout:schemata:timetable.1.0", "department");
    private final static QName _Subject_QNAME = new QName("urn:x-herout:schemata:timetable.1.0", "subject");
    private final static QName _TimetableActivitiesOfFAVStudents_QNAME = new QName("urn:x-herout:schemata:timetable.1.0", "timetableActivitiesOfFAVStudents");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jxtsp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link ActorType }
     * 
     */
    public ActorType createActorType() {
        return new ActorType();
    }

    /**
     * Create an instance of {@link PreregistrationEventsType }
     * 
     */
    public PreregistrationEventsType createPreregistrationEventsType() {
        return new PreregistrationEventsType();
    }

    /**
     * Create an instance of {@link TimetableActivityType }
     * 
     */
    public TimetableActivityType createTimetableActivityType() {
        return new TimetableActivityType();
    }

    /**
     * Create an instance of {@link ProcessedDataType }
     * 
     */
    public ProcessedDataType createProcessedDataType() {
        return new ProcessedDataType();
    }

    /**
     * Create an instance of {@link TimeStampType }
     * 
     */
    public TimeStampType createTimeStampType() {
        return new TimeStampType();
    }

    /**
     * Create an instance of {@link ClientInfoType }
     * 
     */
    public ClientInfoType createClientInfoType() {
        return new ClientInfoType();
    }

    /**
     * Create an instance of {@link PreviousChangeType }
     * 
     */
    public PreviousChangeType createPreviousChangeType() {
        return new PreviousChangeType();
    }

    /**
     * Create an instance of {@link TimetableActionType }
     * 
     */
    public TimetableActionType createTimetableActionType() {
        return new TimetableActionType();
    }

    /**
     * Create an instance of {@link TimetableActivitiesOfFAVStudentsType }
     * 
     */
    public TimetableActivitiesOfFAVStudentsType createTimetableActivitiesOfFAVStudentsType() {
        return new TimetableActivitiesOfFAVStudentsType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link PlaceType }
     * 
     */
    public PlaceType createPlaceType() {
        return new PlaceType();
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreregistrationEventsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-herout:schemata:preregistration.1.0", name = "preregistrationEvents")
    public JAXBElement<PreregistrationEventsType> createPreregistrationEvents(PreregistrationEventsType value) {
        return new JAXBElement<PreregistrationEventsType>(_PreregistrationEvents_QNAME, PreregistrationEventsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TermType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-herout:schemata:timetable.1.0", name = "term")
    public JAXBElement<TermType> createTerm(TermType value) {
        return new JAXBElement<TermType>(_Term_QNAME, TermType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-herout:schemata:timetable.1.0", name = "department")
    public JAXBElement<String> createDepartment(String value) {
        return new JAXBElement<String>(_Department_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-herout:schemata:timetable.1.0", name = "subject")
    public JAXBElement<SubjectType> createSubject(SubjectType value) {
        return new JAXBElement<SubjectType>(_Subject_QNAME, SubjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimetableActivitiesOfFAVStudentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-herout:schemata:timetable.1.0", name = "timetableActivitiesOfFAVStudents")
    public JAXBElement<TimetableActivitiesOfFAVStudentsType> createTimetableActivitiesOfFAVStudents(TimetableActivitiesOfFAVStudentsType value) {
        return new JAXBElement<TimetableActivitiesOfFAVStudentsType>(_TimetableActivitiesOfFAVStudents_QNAME, TimetableActivitiesOfFAVStudentsType.class, null, value);
    }

}
