//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.31 at 10:40:44 dop. CEST 
//


package jxtsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for processedDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processedDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timetableAction" type="{urn:x-herout:schemata:preregistration.1.0}timetableActionType"/>
 *         &lt;element ref="{urn:x-herout:schemata:timetable.1.0}department"/>
 *         &lt;element ref="{urn:x-herout:schemata:timetable.1.0}subject"/>
 *         &lt;element ref="{urn:x-herout:schemata:timetable.1.0}term"/>
 *         &lt;element name="previousChange" type="{urn:x-herout:schemata:preregistration.1.0}previousChangeType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="activity" use="required" type="{urn:x-herout:schemata:preregistration.1.0}activityType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processedDataType", propOrder = {
    "timetableAction",
    "department",
    "subject",
    "term",
    "previousChange"
})
public class ProcessedDataType {

    @XmlElement(required = true)
    protected TimetableActionType timetableAction;
    @XmlElement(namespace = "urn:x-herout:schemata:timetable.1.0", required = true)
    protected String department;
    @XmlElement(namespace = "urn:x-herout:schemata:timetable.1.0", required = true)
    protected SubjectType subject;
    @XmlElement(namespace = "urn:x-herout:schemata:timetable.1.0", required = true)
    protected TermType term;
    @XmlElement(required = true, nillable = true)
    protected PreviousChangeType previousChange;
    @XmlAttribute(required = true)
    protected ActivityType activity;

    /**
     * Gets the value of the timetableAction property.
     * 
     * @return
     *     possible object is
     *     {@link TimetableActionType }
     *     
     */
    public TimetableActionType getTimetableAction() {
        return timetableAction;
    }

    /**
     * Sets the value of the timetableAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimetableActionType }
     *     
     */
    public void setTimetableAction(TimetableActionType value) {
        this.timetableAction = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectType }
     *     
     */
    public SubjectType getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectType }
     *     
     */
    public void setSubject(SubjectType value) {
        this.subject = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link TermType }
     *     
     */
    public TermType getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermType }
     *     
     */
    public void setTerm(TermType value) {
        this.term = value;
    }

    /**
     * Gets the value of the previousChange property.
     * 
     * @return
     *     possible object is
     *     {@link PreviousChangeType }
     *     
     */
    public PreviousChangeType getPreviousChange() {
        return previousChange;
    }

    /**
     * Sets the value of the previousChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviousChangeType }
     *     
     */
    public void setPreviousChange(PreviousChangeType value) {
        this.previousChange = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityType }
     *     
     */
    public ActivityType getActivity() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityType }
     *     
     */
    public void setActivity(ActivityType value) {
        this.activity = value;
    }

}
